### SVM in scikit learn

In [1]:
from sklearn import datasets
import numpy as np

In [2]:
from sklearn.svm import SVC

In [3]:
help(SVC)

Help on class SVC in module sklearn.svm.classes:

class SVC(sklearn.svm.base.BaseSVC)
 |  C-Support Vector Classification.
 |  
 |  The implementation is based on libsvm. The fit time complexity
 |  is more than quadratic with the number of samples which makes it hard
 |  to scale to dataset with more than a couple of 10000 samples.
 |  
 |  The multiclass support is handled according to a one-vs-one scheme.
 |  
 |  For details on the precise mathematical formulation of the provided
 |  kernel functions and how `gamma`, `coef0` and `degree` affect each
 |  other, see the corresponding section in the narrative documentation:
 |  :ref:`svm_kernels`.
 |  
 |  Read more in the :ref:`User Guide <svm_classification>`.
 |  
 |  Parameters
 |  ----------
 |  C : float, optional (default=1.0)
 |      Penalty parameter C of the error term.
 |  
 |  kernel : string, optional (default='rbf')
 |      Specifies the kernel type to be used in the algorithm.
 |      It must be one of 'linear', 'poly',

In [4]:
iris = datasets.load_iris()

In [5]:
X, y = iris.data, iris.target

In [6]:
svm_model = SVC(probability=True)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 42 )

In [9]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, **options)
    Split arrays or matrices into random train and test subsets
    
    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float, int or None, optional (default=0.25)
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        complement of the train size. By default, 

In [10]:
svm_model.fit(X_train,y_train)

/home/singhals/anaconda2/envs/MaskRCNN/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=True, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [11]:
print (svm_model.predict(X_test))
print
print (svm_model.predict_proba(X_test))

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
[[0.01183814 0.94413348 0.04402837]
 [0.92088209 0.04963887 0.02947904]
 [0.02727015 0.03018747 0.94254238]
 [0.01028491 0.93985766 0.04985743]
 [0.01614333 0.88569657 0.09816009]
 [0.94440745 0.03453462 0.02105793]
 [0.01317562 0.98078002 0.00604435]
 [0.01895393 0.09566388 0.88538218]
 [0.0131006  0.83230898 0.15459042]
 [0.00893624 0.98607615 0.00498761]
 [0.01623555 0.17487095 0.8088935 ]
 [0.9537041  0.02525548 0.02104042]
 [0.94898962 0.02877962 0.02223076]
 [0.95296816 0.02669855 0.0203333 ]
 [0.95020572 0.02637476 0.02341952]
 [0.01495801 0.90075654 0.08428545]
 [0.01227996 0.00584    0.98188004]
 [0.00869716 0.98370367 0.00759916]
 [0.01001506 0.94954033 0.04044461]
 [0.01240251 0.00645929 0.9811382 ]
 [0.94760542 0.02965926 0.02273533]
 [0.01437342 0.40708985 0.57853673]
 [0.94825007 0.03102623 0.0207237 ]
 [0.01201995 0.00784844 0.98013161]
 [0.02630748 0.06848557 0.90520695]
 [0.015